connections:
    - ssh.web-01
    - ssh.web-02

remote_path: "/home/bugkillerpro/less"

frontend:
    pre_action:
        - "pwd"
    post_action:
        - "pwd"

backend:
    goos: linux
    goarch: amd64
    pre_action:
        - "pwd"
    post_action:
        - "./less serve restart"
